### ISSUE TITLE
Exports with a period seem to be cropped

### ISSUE THREAD

**Issue by EdgeTechnologiesInc** [vytenisu/npm-dts-webpack-plugin#4]
First I want to thank you for writing this plugin, it's been extremely helpful when trying to create a NPM library written in Typescript.

We have a file in our project that has the following four lines, and for some strange reason in the generated d.ts from this plugin is missing the period and everything following.  I'm wondering if it's an over zealous section of code or Regex that's trying to make sure file extensions aren't used.

```
export * from './src/communication.service';
export * from './src/edge.decorators';
export * from './src/object.util';
export * from './src/uid.service';
```

In the generated d.ts file:

```
export * from './src/communication/index';
export * from './src/edge/index';
export * from './src/object/index';
export * from './src/uid/index;
```

**Comment by EdgeTechnologiesInc** [comment]
FWIW, if we make the following change to the `npm-dts` project it fixes all our problems.  I'm just not sure if it would introduce other issue for other teams.

```
diff --git a/node_modules/npm-dts/dist/index.js b/node_modules/npm-dts/dist/index.js
index 24dc0cf..e037782 100644
--- a/node_modules/npm-dts/dist/index.js
+++ b/node_modules/npm-dts/dist/index.js
@@ -679,7 +679,7 @@ var Generator = /** @class */ (function (_super) {
             path = packageDetails.name + "/" + path;
         }
         path = path.replace(/\\/g, '/');
-        path = path.replace(/\.[^.]+$/g, '');
+        path = path.replace(/\.ts$/g, '');
         path = path.replace(/\.d$/g, '');
         return path;
     };
```

I suppose it probably might if they were using `.tsx` files.

For now I'm just using `patch-package` to make the change for us.

**Comment by vytenisu** [comment]
Hello, @EdgeTechnologiesInc. Apologies for the delay. Will have a look into it in a few days as soon as I get a chance. Need to be careful here and recall why it was done in the first place :D

I can see that purpose of this line was to remove extension BUT it is not necessarily ".ts". It could be ts, tsx, js, jsx and maybe even custom one based on WebPack configuration. I have a few thoughts how to fix it but do not want to rush and risk breaking the tool.

For the sake of test/work-around you could try adding ".ts" to the ending of your imports. Of course, it is not a solution if you have many places like that.

**Comment by EdgeTechnologiesInc** [comment]
Yeah, when I added a .ts to the ending they worked with your tool but the TSLint and Webstorm were not amused.  :)

I updated my comment a little because I forgot to add `/index` to the end of the exports which is what really happens.

**Comment by vytenisu** [comment]
@EdgeTechnologiesInc, could you please check if 1.3.7 version of npm-dts works for you?

This is what I did:
https://github.com/vytenisu/npm-dts/commit/cb8b58601173e7b5ec7884540be7fff1826f7900

I will be closing this issue for now. Should it not fix your problem, please feel free to re-open.

**Comment by JoeFirebaugh** [comment]
That worked!  Thanks!!
